spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oj
    username: root
    password: thinkpadx201
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启下划线(value_name)命名转驼峰(valueName)命名

server:
  address: localhost

judge-server:
  address: localhost
  port: 7000

file-service-server:
  address: localhost
  port: 7001

language-config-path:
  "classpath:language_config.json"